### ISSUE TITLE
Question: Vendoring this package to programmatically use kubedb

### ISSUE THREAD

**Issue by tanner-bruce** [kubedb/apimachinery#394]
Hey folks, we like the kubedb package and are now using it for local development however we want to start using it programmatically, e.g pull in the api definitions and client, however we are running into a pretty big issue due to the use of the forked `k8s.io/apimachinery` package. We are currently using go modules and don't have any issues, but we simply cannot get it to work yet.

I have two questions:
1) any idea on how I could get around needing your forked apimachinery repo?
2) are there plans to remove the need for the forked repo?

Thanks!

**Comment by tamalsaha** [comment]
We have 3 extra commits for apimachinery package. https://github.com/kmodules/apimachinery/commits/ac-1.13.0

If you can get them upstreamed, you are welcome. Btw, what problem are you facing using go modules?

**Comment by AntonMSova** [comment]
Hi Tamal, I'm working with Tanner on getting kubedb setup for local development.  
The errors we are seeing with `apimachinery` are
`go: extracting kmodules.xyz/custom-resources v0.0.0-20190225012057-ed1c15a0bbda
# github.com/kubedb/apimachinery/apis/config/v1alpha1
../../../go/pkg/mod/github.com/kubedb/apimachinery@v0.0.0-20190314030710-334b49d77d81/apis/config/v1alpha1/openapi_generated.go:13098:31: v1.Duration literal.OpenAPISchemaType undefined (type v1.Duration has no field or method OpenAPISchemaType)
../../../go/pkg/mod/github.com/kubedb/apimachinery@v0.0.0-20190314030710-334b49d77d81/apis/config/v1alpha1/openapi_generated.go:13099:31: v1.Duration literal.OpenAPISchemaFormat undefined (type v1.Duration has no field or method OpenAPISchemaFormat)
# kmodules.xyz/custom-resources/apis/appcatalog/v1alpha1
../../../go/pkg/mod/kmodules.xyz/custom-resources@v0.0.0-20190225012057-ed1c15a0bbda/apis/appcatalog/v1alpha1/openapi_generated.go:11944:31: "k8s.io/apimachinery/pkg/apis/meta/v1".Duration literal.OpenAPISchemaType undefined (type "k8s.io/apimachinery/pkg/apis/meta/v1".Duration has no field or method OpenAPISchemaType)
../../../go/pkg/mod/kmodules.xyz/custom-resources@v0.0.0-20190225012057-ed1c15a0bbda/apis/appcatalog/v1alpha1/openapi_generated.go:11945:31: "k8s.io/apimachinery/pkg/apis/meta/v1".Duration literal.OpenAPISchemaFormat undefined (type "k8s.io/apimachinery/pkg/apis/meta/v1".Duration has no field or method OpenAPISchemaFormat)
../../../go/pkg/mod/kmodules.xyz/custom-resources@v0.0.0-20190225012057-ed1c15a0bbda/apis/appcatalog/v1alpha1/openapi_generated.go:13167:40: runtime.RawExtension literal.OpenAPISchemaType undefined (type runtime.RawExtension has no field or method OpenAPISchemaType)
../../../go/pkg/mod/kmodules.xyz/custom-resources@v0.0.0-20190225012057-ed1c15a0bbda/apis/appcatalog/v1alpha1/openapi_generated.go:13168:40: runtime.RawExtension literal.OpenAPISchemaFormat undefined (type runtime.RawExtension has no field or method OpenAPISchemaFormat)
# github.com/kubedb/apimachinery/apis/catalog/v1alpha1
../../../go/pkg/mod/github.com/kubedb/apimachinery@v0.0.0-20190314030710-334b49d77d81/apis/catalog/v1alpha1/openapi_generated.go:14171:31: v1.Duration literal.OpenAPISchemaType undefined (type v1.Duration has no field or method OpenAPISchemaType)
../../../go/pkg/mod/github.com/kubedb/apimachinery@v0.0.0-20190314030710-334b49d77d81/apis/catalog/v1alpha1/openapi_generated.go:14172:31: v1.Duration literal.OpenAPISchemaFormat undefined (type v1.Duration has no field or method OpenAPISchemaFormat)
../../../go/pkg/mod/github.com/kubedb/apimachinery@v0.0.0-20190314030710-334b49d77d81/apis/catalog/v1alpha1/openapi_generated.go:15394:40: runtime.RawExtension literal.OpenAPISchemaType undefined (type runtime.RawExtension has no field or method OpenAPISchemaType)
../../../go/pkg/mod/github.com/kubedb/apimachinery@v0.0.0-20190314030710-334b49d77d81/apis/catalog/v1alpha1/openapi_generated.go:15395:40: runtime.RawExtension literal.OpenAPISchemaFormat undefined (type runtime.RawExtension has no field or method OpenAPISchemaFormat)`

**Comment by tamalsaha** [comment]
Sorry for the slow response. Are you still having this issue?

**Comment by tamalsaha** [comment]
go.mod has been added https://github.com/kubedb/apimachinery/pull/403
