### ISSUE TITLE
Follow semverConvention for go module

### ISSUE THREAD

**Issue by cmoulliard** [kubedb/apimachinery#416]
## Request

Is it possible to tag the releases using `semver` convention [1] as needed to add this module within thefile `go.mod` ? Example : `0.12.0 --> v0.12.0`

[1] https://github.com/golang/go/wiki/Modules#version-selection

**Comment by tamalsaha** [comment]
We use the git tag also as the Docker image tag. I like `kubedb/operator:1.0.0` over `kubedb/operator:v1.0.0`. So, we went with that. Now, Go has this hard coded `v` thing. Secretly, I want Go to not care. But probably have to add that `v`.

Thanks for bringing this to attention.

**Comment by tamalsaha** [comment]
This seems to be fixed in Go 1.13 https://github.com/golang/go/issues/32867 . If that is not the case, we have to add `vX.Y.Z` .

**Comment by tamalsaha** [comment]
Actually it does not work in Go 1.13 . I have filed a bug to see if they respond https://github.com/golang/go/issues/32945

**Comment by tamalsaha** [comment]
Next release will have `v` prefix.
